services:
  postgres:
    container_name: postgres-sql-bn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-network

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - spring-network
    command:
      - "start-dev"

networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
    driver: local